name: daily-update
on:
  schedule:
    - cron: "15 6 * * *"   # 06:15 UTC chaque jour
  workflow_dispatch: {}     # bouton "Run workflow" manuel

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python src/run_pipeline.py

      - name: Commit & push changes
        run: |
          git config user.name "automation-bot"
          git config user.email "automation-bot@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily update" || echo "nothing to commit"
          git push
